# Generated by Django 4.1.6 on 2023-02-17 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('primitive', models.CharField(choices=[('integer', 'integer'), ('string', 'string'), ('number', 'number'), ('boolean', 'boolean')], max_length=7)),
                ('label_ko', models.CharField(max_length=50)),
                ('label_en', models.CharField(max_length=50)),
                ('is_category', models.BooleanField()),
                ('has_length_limit', models.BooleanField(null=True)),
                ('has_range_limit', models.BooleanField()),
                ('default_value', models.TextField(null=True)),
                ('unit_of_value', models.CharField(max_length=10)),
                ('min_length', models.IntegerField(null=True)),
                ('max_length', models.IntegerField(null=True)),
                ('format', models.TextField(null=True)),
                ('pattern', models.TextField(null=True)),
                ('minimum', models.BigIntegerField(null=True)),
                ('maximum', models.BigIntegerField(null=True)),
                ('multiple_of', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
